### PR TITLE
Freeze layers at the same end LSN

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Looks correct at a quick glance. Needs more comments.

Do we need the new `last_lsn` value? It seems unnecessary to me.

**Comment by knizhnik** [comment]
> Looks correct at a quick glance. Needs more comments.
> 
> Do we need the new `last_lsn` value? It seems unnecessary to me.

How else we can efficiently calculate end_lsn of open layer?
Originally we freeze open layers and last_record_lsn. But in this case created layers will always intersect with remaining open layers. So I want to calculate exact upper bound for end_lsn of evicted layers.

**Comment by hlinnaka** [comment]
`last_record_lsn` works, no? What's the difference?

**Comment by hlinnaka** [comment]
> `last_record_lsn` works, no? What's the difference?

Oh, now I think i get it. An open layer might contain more recent WAL that we are not going to flush to disk in this checkpoint. So iteratively, if we flush layer A that contained a record with LSN X, we must also flush any other layers that contain a record with LSN <= X, too. That's what the 'freeze_end_lsn' tracks.

If the workload consists of random updates, it's likely that we will end up flushing everything on every checkpoint, because every in-memory layer will contain records close the last_record_lsn.

Perhaps we should just always flush everything that's in memory. Would seem simpler. So the logic would be that if there are *any* in-memory layers with data older than checkpoint_distance, we flush everything to disk. Otherwise, we do nothing.

**Comment by knizhnik** [comment]
> > `last_record_lsn` works, no? What's the difference?
> 
> Oh, now I think i get it. An open layer might contain more recent WAL that we are not going to flush to disk in this checkpoint. So iteratively, if we flush layer A that contained a record with LSN X, we must also flush any other layers that contain a record with LSN <= X, too. That's what the 'freeze_end_lsn' tracks.
> 
> If the workload consists of random updates, it's likely that we will end up flushing everything on every checkpoint, because every in-memory layer will contain records close the last_record_lsn.
> 
> Perhaps we should just always flush everything that's in memory. Would seem simpler. So the logic would be that if there are _any_ in-memory layers with data older than checkpoint_distance, we flush everything to disk. Otherwise, we do nothing.

Yes, definitely in case of random updates all open layer should be flushed.
But I think that there are other popular workloads:
- append-only tables
- range partitioning
- frequent creation of new tables and population them with data
...
when open layers have minimal intersection.
Such optimization costs almost nothing and doesn't significantly complicate code so  I think it should be done.
As far as I remember originally you have implemented some quite simple eviction algorithm and performance was very bad.
Then you have replace it with current selection of oldest layers and performance significantly improved.
I afraid that with naive eviction of all open layers we will get yet another noticeable performance degradation. Which is even now not so impressing.

**Comment by hlinnaka** [comment]
> > Perhaps we should just always flush everything that's in memory. Would seem simpler. So the logic would be that if there are _any_ in-memory layers with data older than checkpoint_distance, we flush everything to disk. Otherwise, we do nothing.
> 
> Yes, definitely in case of random updates all open layer should be flushed. But I think that there are other popular workloads:
> 
>   * append-only tables
> 
>   * range partitioning
> 
>   * frequent creation of new tables and population them with data
>     ...
> when open layers have minimal intersection.
> Such optimization costs almost nothing and doesn't significantly complicate code so  I think it should be done.
> As far as I remember originally you have implemented some quite simple eviction algorithm and performance was very bad.
> Then you have replace it with current selection of oldest layers and performance significantly improved.
> I afraid that with naive eviction of all open layers we will get yet another noticeable performance degradation. Which is even now not so impressing.

I think it would be ok. It's what happens with mostly random writes here anyway. But I'm OK with this PR too, with the last_lsn, if you prefer. Please add comments, though.

**Comment by knizhnik** [comment]
I am currently changing layers boundaries from [first_record.end_lsn, last_record.end_lsn+1)
to [first_record.start_lsn, last_record.end_lsn) 
It seems to be much more natural, consistent with layer definition and correct (please notice that originally problem was caused by incorrect increment of disk_consistent_lsn using oldest_layer_lsn). But... looks like I opened Pandora's box:(

And yet another detected problem: we may now WAL insert record several times with the same LSN (because it affect multiple pages). This pages may belong to the same relation and same segment. As a result with can have in the layer several records  with the same LSN. What is worser, it can happen at layer boundary. In this case two segments will overlap:
prev_segment.end_lsn > next_segment.first_lsn. I am not sure that interval tree can correctly handle this case.
One of the solution is to assigned to each decoded block it own LSN (which will be somewhere inside WAL record).
Any better proposal?

**Comment by hlinnaka** [comment]
On 26/01/2022 09:50, Konstantin Knizhnik wrote:
> And yet another detected problem: we may now WAL insert record several 
> times with the same LSN (because it affect multiple pages). This pages 
> may belong to the same relation and same segment. As a result with can 
> have in the layer several records with the same LSN. 

Sure.

> What is worser, it can happen at layer boundary. In this case two
> segments will overlap: prev_segment.end_lsn > next_segment.first_lsn.
> I am not sure that interval tree can correctly handle this case.
Sorry, I didn't understand that. What's the problem?

- Heikki

**Comment by knizhnik** [comment]
> On 26/01/2022 09:50, Konstantin Knizhnik wrote: And yet another detected problem: we may now WAL insert record several times with the same LSN (because it affect multiple pages). This pages may belong to the same relation and same segment. As a result with can have in the layer several records with the same LSN.
> Sure.
> What is worser, it can happen at layer boundary. In this case two segments will overlap: prev_segment.end_lsn > next_segment.first_lsn. I am not sure that interval tree can correctly handle this case.
> Sorry, I didn't understand that. What's the problem? - Heikki

We have segment with LSN range [100,200)
Next WAL record with LSN 210 touches several pages (contains N blocks), so we have to insert this record N times.
It can happen that touched pages belongs to this segment.
When we insert WAL record for first block, segment is changed to [100,210)
Then checkpoints happens and layer is frozen and evicted. As a result we have disk layer rel_*_100_210
Now we insert record for next block and have to create new in-memory layer: [200,inf)
Once it is evicted we will have to intersected delta layers, i.e. [100,210) and [200,300)

**Comment by hlinnaka** [comment]
On 26/01/2022 11:36, Konstantin Knizhnik wrote:
> We have segment with LSN range [100,200)
> Next WAL record with LSN 210 touches several pages (contains N blocks), 
> so we have to insert this record N times.
> It can happen that touched pages belongs to this segment.
> When we insert WAL record for first block, segment is changed to [100,210)
> Then checkpoints happens and layer is frozen and evicted. As a result we 
> have disk layer rel_*_100_210
> Now we insert record for next block and have to create new in-memory 
> layer: [200,inf)
> Once it is evicted we will have to intersected delta layers, i.e. 
> [100,210) and [200,300)

The writer that inserts the records holds the write lock on the 
timeline, and it only advances last_record_lsn after it has inserted all 
copies of the record. That should prevent the layer freezing from seeing 
half-finished operations like that.

- Heikki

**Comment by knizhnik** [comment]
I decided not to open Pandora's box now and leave existed layers boundaries.
I have to remove assert that oldest_pending  >= start_lsn because it is not true any more.
Bit all other layers handling logic is preserved.
And my restart test is passed.
I have also added comments.
Do you think that something else should be done in this PR.

I want to commit #1166 but its test sometimes not passed because of the problem fixed in this PR.
So it is better to commit this two PRs together.

**Comment by hlinnaka** [comment]
I added a commit here that adds comments explaining the problem with the logic we had, and how 'last_lsn' solves it. Also, I renamed 'last_lsn' to 'tatest_lsn', and 'oldest_pending_lsn' to just 'oldest_lsn'. The 'oldest_lsn' and 'latest_lsn' are now symmetric.

**Comment by hlinnaka** [comment]
> I decided not to open Pandora's box now and leave existed layers boundaries. 

Ok.

> I have to remove assert that oldest_pending >= start_lsn because it is not true any more. 

Wait, huh? How come?

> I want to commit #1166 but its test sometimes not passed because of the problem fixed in this PR. So it is better to commit this two PRs together.

Makes sense.

**Comment by knizhnik** [comment]
> Wait, huh? How come?

Because oldest_pending_lsn is start LSN of first record in layer and start_lsn is end LSN of first record in the layer.
oldest_pending_lsn is needed only for advancing disk_consistent_lsn. And we really need start LSN of record, otherwise will loose first record in non-evicted layer after restart.

**Comment by hlinnaka** [comment]
> Because oldest_pending_lsn is start LSN of first record in layer and start_lsn is end LSN of first record in the layer. 

No, we don't use a record's start LSN anywhere. 'oldest_pending_lsn' is the *end* LSN of the first record in the layer.

> oldest_pending_lsn is needed only for advancing disk_consistent_lsn. And we really need start LSN of record, otherwise will loose first record in non-evicted layer after restart.

That doesn't sound right. I believe that there is an off-by-one bug somewhere, and I can see that the tests fail if you revert those changes to how we set oldest_pending_lsn. But where exactly, I'm not sure.

**Comment by knizhnik** [comment]
> That doesn't sound right. I believe that there is an off-by-one bug somewhere, and I can see that the tests fail if you revert those changes to how we set oldest_pending_lsn. But where exactly, I'm not sure.

The meaning of disk consistent lsn is that everything below it is already persistent in pageserver storage and so can be deleted from safekeepers. Disk consistent lsn is used as start replication point. Do sfekeeper starts sending WAL from this point. oldest_layer_lsn is used to advance disk_consistent_lsn. No objection till this point?

There was a bug that oldest_layer_lsn points to the end of record. So if we set disk_consistent_lsn to oldest_layer_lsn, then it means that this record is persisted. But actually it is not: it is still present only in opened in-memory layer and will be missed in case of restart.

So there are two solutions:
1. Do not use oldest_layer_lsn for advancing disk_consistent_lsn. This is what I tried to implement in previous PR, using end_lst of last evicted layer. But you explained me why this approach cause starvation in case of not synchronized layers freeze LSNs. 
2. Make oldest_layer_lsn  point to the beginning of record rather then to the end of record. As far as oldest_layer_lsn is used only for adjusting disk_consistent_lsn, it will not cause problems with any other parts of code.

So I find your original implementation of calculating next disk_consistent_lsn simpler and more straightforward than  1). We in any case need to synchronize freeze LSNs. And this is what is done in this PR. 

I do not understand why it sounds wrong. What is wrong from my point of view is current definition of layer boundaries: [first_record.end_lsn...last_record_end_lsn+1)
It contradicts to what is written in comments:
```
    ///
    /// This layer contains all the changes from 'start_lsn'. The
    /// start is inclusive.
    ///
```
IMHO changing layer boundaries to [start_record.first_lsn, last_record.last_lsn) is my natural and clear.
It mostly eliminate need in +-1 manipulations with end_lsn and confusions whether it is inclusive or exclusive, i.e. code like this:
```
       let end_lsn_exclusive = inner.end_lsn.unwrap();
        let end_lsn_inclusive = Lsn(end_lsn_exclusive.0 - 1);
```
I tried to make this change and spent half of the day trying to make it work.
But then I decided that making such dangerous change just before launch is not good idea
and decided to make minimal possible patch. Changing oldest_layer_lsn definition and removing one assert seems to be simplest solution of the problem.

**Comment by hlinnaka** [comment]
On 26/01/2022 23:25, Konstantin Knizhnik wrote:
>     That doesn't sound right. I believe that there is an off-by-one bug
>     somewhere, and I can see that the tests fail if you revert those
>     changes to how we set oldest_pending_lsn. But where exactly, I'm not
>     sure.
> 
> The meaning of disk consistent lsn is that everything below it is 
> already persistent in pageserver storage and so can be deleted from 
> safekeepers. Disk consistent lsn is used as start replication point. Do 
> sfekeeper starts sending WAL from this point. oldest_layer_lsn is used 
> to advance disk_consistent_lsn. No objection till this point?

Ok.

> There was a bug that oldest_layer_lsn points to the end of record. So if 
> we set disk_consistent_lsn to oldest_layer_lsn, then it means that this 
> record is persisted. But actually it is not: it is still present only in 
> opened in-memory layer and will be missed in case of restart.

Hmm, ok.

> So there are two solutions:
> 
>  1. Do not use oldest_layer_lsn for advancing disk_consistent_lsn. This
>     is what I tried to implement in previous PR, using end_lst of last
>     evicted layer. But you explained me why this approach cause
>     starvation in case of not synchronized layers freeze LSNs.
>  2. Make oldest_layer_lsn point to the beginning of record rather then
>     to the end of record. As far as oldest_layer_lsn is used only for
>     adjusting disk_consistent_lsn, it will not cause problems with any
>     other parts of code.
> 
> So I find your original implementation of calculating next 
> disk_consistent_lsn simpler and more straightforward than 1). We in any 
> case need to synchronize freeze LSNs. And this is what is done in this PR.
> 
> I do not understand why it sounds wrong. What is wrong from my point of 
> view is current definition of layer boundaries: 
> [first_record.end_lsn...last_record_end_lsn+1)
> It contradicts to what is written in comments:
> 
> |/// /// This layer contains all the changes from 'start_lsn'. The /// 
> start is inclusive. /// |

It's not wrong as such. All the LSNs refer to a record's end LSN. If you 
read it like that, it's consistent.

I understand now that it's causing trouble with setting 
disk_consistent_lsn. If you take the oldest LSN of the first layer 
that's *not* stored durably to disk, and try to start streaming 
replication from that LSN, you will skip a record. Because the oldest 
LSN is an end LSN, and for replication, you need the start LSN of the 
record. We just don't currently store that information anywhere.

> IMHO changing layer boundaries to [start_record.first_lsn, 
> last_record.last_lsn) is my natural and clear.
> It mostly eliminate need in +-1 manipulations with end_lsn and 
> confusions whether it is inclusive or exclusive, i.e. code like this:
> 
> |let end_lsn_exclusive = inner.end_lsn.unwrap(); let end_lsn_inclusive = 
> Lsn(end_lsn_exclusive.0 - 1); |

Yeah, I see that now. Makes sense.

> I tried to make this change and spent half of the day trying to make it 
> work.
> But then I decided that making such dangerous change just before launch 
> is not good idea
> and decided to make minimal possible patch. Changing oldest_layer_lsn 
> definition and removing one assert seems to be simplest solution of the 
> problem.

It just feels very strange to me that the oldest_lsn can be smaller than 
the start_lsn. Agreed that that's probably the smallest fix right now.

Another straightforward solution is to flush all in-memory layers, if 
you're going to flush any of them. That way, disk_consistent_lsn is 
always set to last_record_lsn, not to the oldest LSN of any layer.)

- Heikki

**Comment by knizhnik** [comment]
> It's not wrong as such. All the LSNs refer to a record's end LSN. If you
read it like that, it's consistent.

Well, this is an issue of agreements.
But LSN is a point, while WAL record is  a range of LSNs. And it is the point of confusion.

> It just feels very strange to me that the oldest_lsn can be smaller than
the start_lsn.

+1
This is why I first of all decided to change start_lsn as well. But unfortunately it cause cascade of changes and I failed to make it work in some reasonable amount of time.

> Another straightforward solution is to flush all in-memory layers, if
you're going to flush any of them.

Yes, it is true.
As I already wrote, I afraid that eviction of all layers at each checkpoint will cause significant degrade of performance (especially with 1 second checkpoint interval). At lest we should handle case when no layer is evicted at all because none of them cross checkpoint distance.

So, right now this PR is passing tests including my shell script which performs restarts after killing all postgres/pageserver/safekeeper processes. Should we commit it as it is or you prefer more straightforward solution (evict all layers)? In this case we can  throw away `oldest_layer_lsn` at all because it is not needed for any other purpose... Please also notice that this "straightforward solution" is not simpler and also requires two loops: first one to check if any layer cross checkpoint distance and if so, then second loop should evict all open layers.

**Comment by hlinnaka** [comment]
> Yes, it is true. As I already wrote, I afraid that eviction of all layers at each checkpoint will cause significant degrade of performance (especially with 1 second checkpoint interval). At lest we should handle case when no layer is evicted at all because none of them cross checkpoint distance.

Yeah, checking for checkpoint distance is important.

> So, right now this PR is passing tests including my shell script which performs restarts after killing all postgres/pageserver/safekeeper processes. Should we commit it as it is or you prefer more straightforward solution (evict all layers)?

Let's commit this. Please check and fix the comments, I think some of the comments I added are not accurate, now that oldest_lsn is the record's start LSN.

> In this case we can throw away `oldest_layer_lsn` at all because it is not needed for any other purpose... Please also notice that this "straightforward solution" is not simpler and also requires two loops: first one to check if any layer cross checkpoint distance and if so, then second loop should evict all open layers.

Well, the layers are in oldest-first order, so you can peek at the first one, and check if it crosses checkpoint distance. And if it does, evict all of them. You could also get rid of the "generation" stuff there.

But since PR works, let's just get it in.

**Comment by knizhnik** [comment]
@hlinnaka  are there some other comments I need to fix?

**Pull request merged**
