### PR TITLE
Move xlog_utils.rs to postgres_ffi module.

### PR DESCRIPTION
**Pull request by hlinnaka**
I had copy-pasted these functions to a few other places. Clean that up,
move them to a common module, and add some comments.

### CODE REVIEW

**Comment by hlinnaka** [comment]
I'd also like to move pageserver::ZTimelineId to some common module. At first I planned to move it to postgres_ffi, too, but on second thoughts, pageserver::ZTimelineId is a zenith-only concept, so it doesn't really belong in postgres_ffi. Perhaps we need yet another common module for that. I'm tempted to move it to the 'zenith' module, because that sounds generic enough, but currently 'zenith' contains just the CLI. Perhaps rename current 'zenith' to 'zenith-cli', and create a new 'zenith' module to hold ZTimelineId. Then again, if we don't have anything else to put in that module, having a separate module for it seems like overkill. So not sure what to do..

**Comment by ericseppanen** [comment]
Did you forget to `git add` a file?

**Comment by hlinnaka** [comment]
> Did you forget to `git add` a file? This commit deletes a lot of code but doesn't add it back anywhere.

It's present in xlog_utils.rs. The removed code was copy-pasted from xlog_utils.rs

**Review by knizhnik — COMMENTED** [review]
In Postgres TimeLineID is 32-bit number.
Comment in lib.rs says that it is 32-byte ID but it is defined as 16-byte array:
```
// Zenith Timeline ID is a 32-byte random ID.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ZTimelineId([u8; 16]);
```

I wonder why it is not just u32?

**Comment by hlinnaka** [comment]
So, two things here:

> Comment in lib.rs says that it is 32-byte ID but it is defined as 16-byte array:
> 
> ```
> // Zenith Timeline ID is a 32-byte random ID.
> #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
> pub struct ZTimelineId([u8; 16]);
> ```

Ah, good catch. The comment is wrong, it is indeed a 16-byte random ID.

> In Postgres TimeLineID is 32-bit number.
> 
> I wonder why it [ZTimelineId] is not just u32?

Zenith timeline ids is different from PostgreSQL timeline IDs. They serve a similar purpose: to differentiate between two "histories" of the same cluster. In zenith, you can create a new timeline with the `zenith branch` command, and then you can run Postgres on the old and the new timeline simultaneously.

Perhaps we should just use PostgreSQL timelines, to have one fewer concept to deal with. However, PostgreSQL timeline IDs are a bit cumbersome:

- PostgreSQL enforces that the timeline IDs are in ascending order in any timeline history.
- PostgreSQL timeiline IDs are only 32 bits wide.

Those limitations mean that we cannot generate a new PostgreSQL timeline ID by just generating a random number. And that in turn is problematic for the "pull/push" workflow that we have been talking about, where you have a local copy of the zenith repository, and then you push the changes to a remote server. When you work "detached" from the remote server, you cannot create a PostgreSQL timeline ID that's guaranteed to be different from all existing timelines in the remote server. For example, if two people are having a clone of the repository on their laptops, and they both create a new branch with  different name. What timeline ID would they assign to their branches? If they pick the same one, and later try to push the branches to the same remote server, they will get mixed up.

So I think it's very handy to have a timeline id that's wide enough that you can create one at random and be sure that it's universally unique. That's what ZTimelineId is.

**Comment by hlinnaka** [comment]
> So I think it's very handy to have a timeline id that's wide enough that you can create one at random and be sure that it's universally unique. That's what ZTimelineId is.

I put that explanation in a code comment: https://github.com/zenithdb/zenith/pull/55, please have a look

**Pull request merged**
