### PR TITLE
WIP add unit test for find_end_of_wal().

### PR DESCRIPTION
**Pull request by lubennikovaav**
I wrote a dummy test for #228
Now it simply runs `find_end_of_wal` on files that I picked from another test.
That is enough to catch XLOG_PAGE_MAGIC problem.

But I also want to add tests for several specific cases with contrecords:
- simple contrecord (xlogrecord that crosses XlogPage border)
- long contrecord that can jump over a page
- contrecord that crosses wal segment border (to check it with long page header)

Are there any good practices for generating PostgreSQL WAL for tests?

### CODE REVIEW

**Comment by kelvich** [comment]
> Are there any good practices for generating PostgreSQL WAL for tests?

I was thinking about that few times but didn't came up with any good solution. Some ideas:

* we can save interesting cases of walbuffers in git and have some infrastructure to put that buffers into files / sockets when running tests. Since each wal segment needs header and that header would be analyzed it is not easy to setup wal segment that would have only last buffer for example (but with some amount of hacking it should be possible). With walreceiver that may be slightly easier as it can start reading not only from segment start.
* Write another main function to postgres, like --wal-redo does. E.g. postgres --generate-unconvenient-wal which would start and manually put records that you mentioned to the end of wal.
* Try to force such wal from sql level and if that is not possible to do deterministically we can write stored procedure which manually craft that records.

**Review by hlinnaka — COMMENTED** [review]
Including WAL files isn't a great way to test, but it's better than nothing..

What is special about this piece of WAL? What records or offsets in the WAL file do you need to reproduce the bug? Let's add least explain that in the test comments, so that if someone wants to recreate the WAL, they'll know what it needs to contain. We will need to do that when we add support for PostgreSQL v15.

**Comment by kelvich** [comment]
Hm, if we are going to run tests over whole WAL 16MB-segment I would rather put that WAL-files at some http endpoint rather then in repository.

**Review by ericseppanen — COMMENTED** [review]
Yay, unit tests! :)

**Pull request closed without merging**
