### PR TITLE
Fix tone down compact log chatter

### PR DESCRIPTION
**Pull request by dhammika**
Signed-off-by: Dhammika Pathirana <dhammika@gmail.com>

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
> Any objections to logging only partitions with deltas?

https://github.com/zenithdb/zenith/pull/1428

**Review by SomeoneToIgnore — APPROVED** [review]

**Comment by SomeoneToIgnore** [comment]
image

WDYT, should we make the whole log `debug` instead and remove that `return`?

**Comment by dhammika** [comment]
Isn't `return` to skip scanning once we've found a layer that satisfies delta threshold? No point scanning further if we already know that. 
It can be still quite chatty if the delta layers don't meet threshold criteria.

**Comment by SomeoneToIgnore** [comment]
My bad, I've meant `continue`, related to this logging removal.
But looks like it's already in the works: https://github.com/zenithdb/zenith/pull/1435

**Pull request merged**
