### PR TITLE
Add CONTRIBUTING.md with some ground rules for submitting PRs.

### PR DESCRIPTION
**Pull request by hlinnaka**
Let's try to rachet up our code quality, but at the same time keep the
bureaucracy low.

### CODE REVIEW

**Comment by funbringer** [comment]
Do review guidelines & best practices belong here, or should we create another *.md?

**Comment by kelvich** [comment]
I fixed indentation in numbered list entries -- looked simpler to fix than to comment. Feel free to revert if that format was intentional.

**Comment by hlinnaka** [comment]
> Do review guidelines & best practices belong here, or should we create another *.md?

Let's add it here. If this grows too large, we can split it.

**Comment by hlinnaka** [comment]
> I fixed indentation in numbered list entries -- looked simpler to fix than to comment. Feel free to revert if that format was intentional.

Thanks, I squashed it here.

**Comment by lubennikovaav** [comment]
While we're on it, I have a question about CI.
It would be perfect to keep it green, but we already have a few floating bugs (i.e #176).
Let's agree on what to do with such issues. 

Also, what should we do with newly added tests that fail? I.e. #188 
Options are:
- merge them in a failing state to annoy everyone until its fixed :)
- hold them in PR and merge in main only when the fix is ready.
- merge them with some allow_failure setting.

**Comment by hlinnaka** [comment]
> While we're on it, I have a question about CI.
> It would be perfect to keep it green, but we already have a few floating bugs (i.e #176).

:-(

> Let's agree on what to do with such issues.
> 
> Also, what should we do with newly added tests that fail? I.e. #188
> Options are:
> 
>     * merge them in a failing state to annoy everyone until its fixed :)
> 
>     * hold them in PR and merge in main only when the fix is ready.
> 
>     * merge them with some allow_failure setting.

Ideally, it gets fixed quickly. Make sense to hold it in a PR in that case, until it's fixed. 

But if it cannot be fixed quickly for some reason, the choice is harder. Tests that are allowed to fail are pretty useless. But is it still more useful than not having the test at all? Keeping it in a PR is probably the best option. In a PR, at least there's some visibility on it, but it's not blocking others.

**Comment by ericseppanen** [comment]
> Also, what should we do with newly added tests that fail?

Another option: pytest has an [`xfail`](https://docs.pytest.org/en/reorganize-docs/new-docs/user/xfail.html) attribute for tagging tests that should be run, but aren't expected to pass.

**Comment by hlinnaka** [comment]
Pushed.

> > Also, what should we do with newly added tests that fail?
> 
> Another option: pytest has an [`xfail`](https://docs.pytest.org/en/reorganize-docs/new-docs/user/xfail.html) attribute for tagging tests that should be run, but aren't expected to pass.

Right, that's Ann's option 3, "merge them with some allow_failure setting". It begs the question, what's the point of the test if it's allowed to fail? There is no easy answer, really. The best solution is to fix the bug that's causing it to fail. If that's not immediately possible, then you need to somehow remember to do it later.

**Pull request merged**
