### PR TITLE
Fix macOs compilation

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
https://docs.rs/libc/latest/src/libc/unix/linux_like/linux/mod.rs.html#1

`prctl` and `PR_SET_PDEATHSIG` are Linux-specific and do not work, according to `XXX` comment, so I've removed them to restore macOs compilation capabilities

### CODE REVIEW

**Review by ololobus — APPROVED** [review]
Oh, my bad, thanks! I now switched to Linux as my primary system, so haven't noticed this.

It seems that you committed some different version of `vendor/postgres` is it intentional?

BTW, it's still not clear for me what is the best practice to kill the child process (postgres), when main exits / panics. Previously I had a guard wrapper, which were killing postgres by stored pid, when main panics, but then @funbringer told me about PR_SET_PDEATHSIG. Which seemed to me as a god option to use :)

**Comment by SomeoneToIgnore** [comment]
Thanks, no postgres changes slip unnoticed :) 

Yes, not clear for me either how to properly do it, alas.

**Comment by funbringer** [comment]
Well, the reason it didn't work out is that it should be used in a **child**, not parent; we should understand this option as "send me a signal when my parent dies". Note that (per `man 2 prctl`) **"The parent-death signal setting is cleared for the child of a fork(2)."**. Hence, one's supposed to do the following:

1. `fork` the process.
2. Inside a fork, call `prctl(PR_SET_PDEATHSIG, <SIGNAL>)`
3. `execve` into a new program.

I'm not going to pretend that this is easy to code up, as there definitely are race conditions to look out for, e.g. (per `man 2 prctl`) "If the parent thread and all ancestor subreapers have already terminated by the time of the PR_SET_PDEATHSIG operation, then no  parent-death signal is sent to the caller.". This one should be mitigated by a pipe which the child process should read from upon calling the `prctl` syscall; if the pipe is dangling, the parent must have died, so we should exit immediately.

If you ask me, I believe there's two things we could learn from this:

* We definitely should `cfg`-out OS-specific features. In this particular case the removal is **completely justified**, since the code was broken, but it's not the *best* way to manage things in the long run. We have a diverse team of people with different backgrounds, and you never know who and when might come up with a good idea. When you lose a grip of a stream of PRs, the magical disappearances of interesting pieces are almost guaranteed to catch you off guard. I'd love to see a "justification" procedure for such "code cleanups", or at least a "final commit period" (24 hours) to give everyone time to react. By the way, @ololobus thanks for pinging me!

* I'm reasonably sure that in most cases we shouldn't remove anything unless we're able to prove the claim set by an unsure comment.

**Comment by ololobus** [comment]
> Well, the reason it didn't work out is that it should be used in a child, not parent; we should understand this option as "send me a signal when my parent dies". Note that (per man 2 prctl) "The parent-death signal setting is cleared for the child of a fork(2)."

Ugh, I've eyeballed the docs a couple of times, but got it in a way that fork clears this up, but if you exec a new child it's applied to it as well. Anyway, we should definitely get back to it, as I test zenith_ctl locally from time to time and I don't like this orphaned Postgres process it leaves behind. Thanks for the comment. Put it on todo into #1070

**Pull request merged**
