### PR TITLE
Fix checkpoint.nextXid update

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Let's add unit tests for this. And a comment to point out that when we start supporting commit_ts, this needs to be adjusted.

**Comment by hlinnaka** [comment]
The test fails for me, with or without the code changes, like this:
```
FAILED batch_others/test_next_xid.py::test_next_xid - psycopg2.errors.InternalError_: could not open relation with OID 16384
```
Is this the same issue as #1140 ?

**Comment by hlinnaka** [comment]
Added a commit with some minor cleanups in the test

**Comment by knizhnik** [comment]
> The test fails for me, with or without the code changes, like this:
> 
> ```
> FAILED batch_others/test_next_xid.py::test_next_xid - psycopg2.errors.InternalError_: could not open relation with OID 16384
> ```
> 
> Is this the same issue as #1140 ?

Yes, at my system test is passed in this branch without GC/checkpointer fixes.
But them can obviously cause this error, moreover I got the same error  "could not open relation with OID" with restart test before #1175 PR

**Comment by hlinnaka** [comment]
Added a unit test, too. Mostly as a form of documentation and to give a example with concrete values of what it does.

**Pull request merged**
