### PR TITLE
Bump vendor/postgres to use rebased on top of REL_14_BETA1 version

### PR DESCRIPTION
**Pull request by ololobus**
Currently it uses https://github.com/zenithdb/postgres/tree/main_rbs. I'm going to replace `zenithdb/postgres#main` with `zenithdb/postgres#main_rbs` and change this commit to point there if all CI tests show green.

### CODE REVIEW

**Review by lubennikovaav — APPROVED** [review]
Don't know how to review this rebase. I think that we may rely on tests here.

I suggest squashing recent fixes to patches, while on it.

**Comment by hlinnaka** [comment]
> Don't know how to review this rebase. I think that we may rely on tests here.

Yeah. Were there any non-trivial conflicts that needed manual fixing?

**Comment by ololobus** [comment]
> Yeah. Were there any non-trivial conflicts that needed manual fixing?

No, only some renaming during vacuumlazy.c refactoring and conflicts in the CREATE / ALTER TABLE tests due to the new tests and detail messages.

I did some minor code style fixes (like trailing whitespaces) and run `pgindent` on `contrib/zenith`. Also squashed all hotfixes into corespondent patch-commits, but left some more complex or with TODO entries intact.

Currently, all tests passed several times locally and in CI. However, once it failed in CI with `FAILED (test process exited with exit code 1)` during pg_regress tests debug / isolations tests (but passed pg_regress tests release in the same time) with only
```
ERRO error: Broken pipe (os error 32), location: pageserver::page_service, pageserver/src/page_service.rs:436
```
in the pageserver log.

**Comment by ololobus** [comment]
So if no objections, I am going to force-push postgres#main with this new branch and update this PR to point there

**Comment by hlinnaka** [comment]
> So if no objections, I am going to force-push postgres#main with this new branch and update this PR to point there

+1

**Pull request merged**
