### PR TITLE
imported RFCs from https://github.com/zenithdb/rfcs

### PR DESCRIPTION
**Pull request by stepashka**
imported RFCs from https://github.com/zenithdb/rfcs
added
- author names
- month and a year when the RFC was created
- link to the original PR

### CODE REVIEW

**Comment by stepashka** [comment]
JFYI @MMeent , the RFCs are migrating to this repo soon

**Review by kelvich — APPROVED** [review]
Looks good, thanks!

**Comment by hlinnaka** [comment]
Is this really a good idea? These RFCs don't describe the code as it stands, but various early ideas and design alternatives. I think it's confusing to have them in the main repo.

**Comment by stepashka** [comment]
@hlinnaka ,

> These RFCs don't describe the code as it stands, but various early ideas and design alternatives.

IMHO the past RFCs are not supposed to be kept up to date as implementation evolves. they describe the reasoning and decision making process of the past. they are valuable and useful for other reasons too.
i was hoping that with that disclaimer in readme it shouldn't be confusing.
@kelvich  was going to import this disclaimer in another a PR soon.

> Is this really a good idea? 

I'll park this till @kelvich creates a PR I've mentioned
the PR would describe the Tech Design RFC process.
he is going to add any time now
once we agree on the new RFC process, we can decide if it makes sense to import the old stuff here too and archive the old repo.
the reasons for keeping the Tech Design RFCs near the code are:
- this allows to have a single PR for both, the Tech Design RFC and the implementation (but doesn't enforce to have just one)
- this makes it easier to evolve the implementation and the Tech Design RFC together
- allows to use the same labels and other metadata for RFC PRs as for the other issues
- makes it easier to notice what the others are working on and kick start the Tech Design RFC process (assumption here is that main repo is updated locally more frequently, if not daily, while the RFC repo is separate and people may overlook the changes and PRs there)

**Pull request closed without merging**
