### PR TITLE
Fix command tag returned to client on IDENTIFY_SYSTEM command.

### PR DESCRIPTION
**Pull request by hlinnaka**
It's like a SELECT that returns one row.

### CODE REVIEW

**Comment by hlinnaka** [comment]
I extracted this change to a separate PR from PR #272 so that it can be reviewed separately.

Should we have tests for this? Clients generally don't care much about the command tags, and there aren't many tests for them in Postgres either, but still..

**Comment by knizhnik** [comment]
I was just my small mistyping. I do not think that we need test for it. Actually  wal_keeper worked even without this fix (I expect because libpq is not so strict cocerning tag format).

**Review by knizhnik — APPROVED** [review]

**Comment by hlinnaka** [comment]
Hmm, looking at `walsender.c`, it seems to me that the corresponding code in PostgreSQL actually is returning `IDENTIFY_SYSTEM` as the command tag:
```
		case T_IdentifySystemCmd:
			cmdtag = "IDENTIFY_SYSTEM";
			set_ps_display(cmdtag);
			IdentifySystem();
			EndReplicationCommand(cmdtag);
			break;
...
void
EndReplicationCommand(const char *commandTag)
{
	pq_putmessage('C', commandTag, strlen(commandTag) + 1);
}
```
I haven't looked at what actually happens with a TCP sniffer or anything, but if that's true, we should just forget about this?

**Comment by knizhnik** [comment]
Oops,
So my original code was correct.
Let's just close this PR.
Sorry, for this "fix".

**Pull request closed without merging**
