### PR TITLE
Fix deadcode warnings

### PR DESCRIPTION
**Pull request by dhammika**
Signed-off-by: Dhammika Pathirana <dhammika@gmail.com>

### CODE REVIEW

**Comment by petuhovskiy** [comment]
It seems to be introduced by #1290. I think we can fix this warning by actually using conf. In persist function, we should skip calls to fsync() when `conf.no_sync` is set.

**Comment by dhammika** [comment]
Thanks, I'll check it. 
Not sure why this would break e2e tests though. I didn't see that crate used elsewhere.

**Comment by petuhovskiy** [comment]
> Not sure why this would break e2e tests though.

It shouldn't, it looks more like flaky tests or some other issue.

**Review by petuhovskiy — APPROVED** [review]
LGTM

**Pull request merged**
