### PR TITLE
Buffered read

### PR DESCRIPTION
**Pull request by knizhnik**
The goal of this optimization is to improve disk IO for delta_layer.
To reconstruct page we need to read multiple wal records (some of them can be very small).
It is very inefficient to read each record individually.
So I have changed delta layer index to contain not only offsets of versions (blobs), but also their size and will_init flag. It will allow to determine file range which needs to be extracted and read it using one syscall.

I noticed that the same format of storing blobs is used i image layer and inmem layer. May be this approach can be also used there and functions for working with blobs from utils.rs can be completely removed. But unit of access in image layer  is 8k page. And we rarely need to fetch multiples pages from image layer at once. And inmem layer is now accessed through page cache.

So if you find this approach reasonable, I will do more refactoring.

### CODE REVIEW

**Comment by hlinnaka** [comment]
Yeah, something like this is a good start. Storing the will_init flag in the index makes a lot of sense. Storing the size also makes sense, but it has the downside that it makes the values stored in the index larger, increasing its memory use. (Well, currently it's a u64 with or without this PR: but the opportunity cost here is that instead of storing the size in the value, we could store just the offset in a u32).

Did you measure the performance benefit from this?

**Comment by knizhnik** [comment]
On my page reconstruction test:
```
create table t2 as select generate_series(1,10000000);
select count(*) from t2;
```
with disabled GC, compaction, autovacuum and wal_redo_hints
 
| branch                           | seqplan | parplan |
| -------------------------- | --------- | --------- |
| buffered_read                | 23327 | 12700 |
| heikki-kvstore                | 206556 | 173609 |
| main                               | 24787  | 11751   |
| rust_redo_handlers       | 16723  |   5460   |
| wal_redo_optimization | 20407  |   8172   | 

So it provides improvement almost ten times.

**Comment by knizhnik** [comment]
> Well, currently it's a u64 with or without this PR: but the opportunity cost here is that instead of storing the size in the value, we could store just the offset in a u32
Total size of layer is not changed in any way. Index size in memory will be also the same, even if we change position to u32, because VecMap is storing (K,V) pair where k=Lsn, so due to alignment size of pair will be 16 bytes

**Comment by hlinnaka** [comment]
> On my page reconstruction test:
> 
> ```
> create table t2 as select generate_series(1,10000000);
> select count(*) from t2;
> ```
> 
> with disabled GC, compaction, autovacuum and wal_redo_hints
> branch 	seqplan 	parplan
> buffered_read 	23327 	12700
> heikki-kvstore 	206556 	173609
> main 	24787 	11751
> rust_redo_handlers 	16723 	5460
> wal_redo_optimization 	20407 	8172
> 
> So it provides improvement almost ten times.

To reproduce these tests, I added variants to our seqscan test, see https://github.com/zenithdb/zenith/pull/1378. With that:

```
ZENITH_BIN=../target/release/  pytest-3 --runslow -k zenith performance/test_seqscans.py

main:

test_seqscans[zenith-100000-100-0].table_size: 3629056 bytes
test_seqscans[zenith-100000-100-0].run: 2.227 s
test_seqscans[zenith-10000000-1-0].table_size: 362479616 bytes
test_seqscans[zenith-10000000-1-0].run: 11.151 s
test_seqscans[zenith-10000000-1-4].table_size: 362479616 bytes
test_seqscans[zenith-10000000-1-4].run: 8.446 s


heikki-kvstore:

test_seqscans[zenith-100000-100-0].table_size: 3629056 bytes
test_seqscans[zenith-100000-100-0].run: 14.732 s
test_seqscans[zenith-10000000-1-0].table_size: 362479616 bytes
test_seqscans[zenith-10000000-1-0].run: 50.811 s
test_seqscans[zenith-10000000-1-4].table_size: 362479616 bytes
test_seqscans[zenith-10000000-1-4].run: 39.235 s

store-size-in-delta-index:

test_seqscans[zenith-100000-100-0].table_size: 3629056 bytes
test_seqscans[zenith-100000-100-0].run: 12.481 s
test_seqscans[zenith-10000000-1-0].table_size: 362479616 bytes
test_seqscans[zenith-10000000-1-0].run: 22.006 s
test_seqscans[zenith-10000000-1-4].table_size: 362479616 bytes
test_seqscans[zenith-10000000-1-4].run: 16.780 s
```

So this PR definitely helps. Not 10x but about 2x, which is still a lot. However, it's still much slower than 'main'.

I disabled the code to cache materialized page versions on the heikki-kvstore, I think that may explain the big difference in the test with a smaller table. It repeats the same scan 100 times, so caching the latest materialized page would help a lot with that.

**Comment by knizhnik** [comment]
The reason why heikki-kvstore is 10x slower than main (with disabled checkpointer) is that "main" doesn't evict in-memory layer in this case, while new version does:  check_checkpoint_distance in walreceiver.
As a result, new version has to reconstruct pages from delta layers. And without buffering it is extremely slow.

I think that in your test you didn't change pageserver configuration parameters and this is why just 2 times instead of 10.

But it is IMHO really interesting question: should we flush inmemory layers in main thread? 
From one side: it allows to limit size of in-memory layer (and so produced delta layer). It is actually important, especially taken in account that there are several places where we assume that layer size (and offset) fits in u32.
From the other side: it can slowdown wla receiver and so reduce performance. It may be preferable to perform such expensive operations like flushing data to the disk in background.

Is there warranty now that maximal layer size can not be larger than some threshold (128Mb for example)?

**Pull request closed without merging**
