### PR TITLE
Add cli start/stop test

### PR DESCRIPTION
**Pull request by dhammika**
Signed-off-by: Dhammika Pathirana <dhammika@gmail.com>

Add a test for #1260

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]

**Comment by LizardWizzard** [comment]
I wonder why the rest of the checks were not triggered? If I'm not mistaken formatting check started to fail on main since this PR

**Comment by SomeoneToIgnore** [comment]
Remember fixing python formatting already before this PR, so it's something older.

**Comment by dhammika** [comment]
Didn't see any ci checks though. Perhaps I missed pre-commit hooks.

**Comment by LizardWizzard** [comment]
It is possible to merge before CI checks complete. CI is always the source of truth, so there is no such checks that are present in pre-commit hooks and do not run in CI

**Pull request merged**
