### PR TITLE
Fix for 1bfade8a. Use correct xid to unlink TwoPhase file

### PR DESCRIPTION
**Pull request by lubennikovaav**
issue #422

### CODE REVIEW

**Comment by hlinnaka** [comment]
A test would be nice. But I know that's hard, since Postgres won't complain about extra twostate files.. Maybe peek directly in the pg_twophase directory of the cluster to see that there aren't any extra entries?

**Comment by lubennikovaav** [comment]
> A test would be nice. But I know that's hard, since Postgres won't complain about extra twostate files.. Maybe peek directly in the pg_twophase directory of the cluster to see that there aren't any extra entries?

PostgreSQL removes these files at the node start. For this test, we could create compute node, check files and then start a node.
But it requires changes in our testing framework, namely #368 PR. Looks like it's time to finish it...

**Comment by hlinnaka** [comment]
Hmm, does the new test fail without the code fix? I thought you would need to commit a prepared transaction before the checkpoint to see a difference.

**Comment by lubennikovaav** [comment]
@hlinnaka, the fix was merged with your commit 1bfade8, so this PR is only about test now.

**Review by hlinnaka — APPROVED** [review]

**Pull request merged**
