### PR TITLE
Change default parameters for back pressure and PG checkpoints.

### PR DESCRIPTION
**Pull request by hlinnaka**
Fixes issue #1238 and #1189. Extracted from PR #1194, with some comment
editorialization by me.

Author: Konstantin Knizhnik <knizhnik@zenith.tech>

### CODE REVIEW

**Comment by hlinnaka** [comment]
Replying to @lubennikovaav's comment at PR #1194:
> I am a bit worried that with these new limits backpressure won't be covered by our tests anymore.
> So, maybe we can add some test that specifically covers backpressure?
> 
> I.e. set small values for lag parameters, perform writes and ensure that lag is within the limit using for example this query
> 
> select pid, pg_wal_lsn_diff(pg_current_wal_lsn(),sent_lsn) as pending_lag,
> pg_wal_lsn_diff(pg_current_wal_lsn(),write_lsn) as write_lag,
> pg_wal_lsn_diff(pg_current_wal_lsn(),flush_lsn) as flush_lag,
> pg_wal_lsn_diff(pg_current_wal_lsn(),replay_lsn) as apply_lag
> FROM pg_stat_get_wal_senders();

That's a valid concern. This PR makes the write lag limit smaller than before so we'll get more testing of that. OTOH, this removes raises the flush lag and removes the apply lag altogether. We didn't have any tests for this previously either but we should. It's not easy to make a robust test, because if the pageserver keeps up with processing the WAL faster than it's produced, all the lags will stay small without invoking backpressure. So I think it will need something like the failpoints from https://github.com/zenithdb/zenith/pull/1043.

**Review by knizhnik — APPROVED** [review]

**Review by arssher — APPROVED** [review]

**Comment by hlinnaka** [comment]
Looks like this did *not* fix the flaky test_isolation test.

**Comment by knizhnik** [comment]
> Looks like this did _not_ fix the flaky test_isolation test.

As I wrote, I have to change max_replication_write_lag to 10Mb to make this test passed.
500Mb value for max_replication_write_lsn was taken in the assumption that average WAL apply speed is about 10Mb/sec. So 500Mb corresponds to 50 minutes, which is less than 1 minute timeout. But in debug mode applying speed is about ~10 times slower.

So, what we can do?
1. Reduce max_replication_write_lsn  to let's say 10-50Mb
2. Run tests only in release mode
3. Do not use relsize cache for smgr_exists (implicit back pressure)

Third option seems to strange because it only hide real problem.

**Comment by hlinnaka** [comment]
> > Looks like this did _not_ fix the flaky test_isolation test.
> 
> As I wrote, I have to change max_replication_write_lag to 10Mb to make this test passed. 500Mb value for max_replication_write_lsn was taken in the assumption that average WAL apply speed is about 10Mb/sec. So 500Mb corresponds to 50 minutes, which is less than 1 minute timeout. But in debug mode applying speed is about ~10 times slower.

I see.

> So, what we can do?
> 
>     1. Reduce max_replication_write_lsn  to let's say 10-50Mb
> 
>     2. Run tests only in release mode
> 
>     3. Do not use relsize cache for smgr_exists (implicit back pressure)
> 
> 
> Third option seems to strange because it only hide real problem.

The thing is, the CI is broken. That's blocking everyone else. We've now spent a while trying to fix it with backpressure, but it's clearly not working great either (see also https://github.com/zenithdb/zenith/issues/1242). It's time to stop fumbling, and revert to the last known good state, which means #3. Then take the time to fix the backpressure mechansim properly.

As the long term solution, I'd go with #1, i.e. reduce the default max_replication_write_lsn to a small value. In production, it can be set higher, based on how fast the WAL receiver can process WAL in production. But right now, to put out the fire, let's do #3.

**Pull request closed without merging**
