### PR TITLE
Gc only

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Can you remove the BufferTag -> ObjectTag changes from this PR, please? It's not needed for GC.

**Comment by hlinnaka** [comment]
There are a bunch of compiler warnings about unused imports.

**Comment by knizhnik** [comment]
> Can you remove the BufferTag -> ObjectTag changes from this PR, please? It's not needed for GC.

Sorry, currently GC is using list_objects iterator which returns ObjectTag.
It is possible to implement GC using list_rels, but it requires to create yet another implementation (third branch doing the same thing!). Why? GC as itself is not so critical component. And it seems to me that everybody agreed to replace fake forknumbers with enum (ObjectTag). Actually it was not my proposal. I found this change too massive and not strictly needed. But after two days of coding I have done it and also rewrite changes from  page_server_nonrel_wal_redo according to the new model. Frankly speaking the last thing I want to do now is to implement yet another GC version based on old KV model.

**Comment by kelvich** [comment]
We discussed this pr with @knizhnik and decided to wait with it until nonrel_wal lands in main

**Comment by knizhnik** [comment]
Old API doesn't allow to implement GC, because there is no way to iterate through all relations (of all databases).
So to be able to implement GC I neeed new API and it is based on new ObjectTag/ObjectValue.

**Comment by hlinnaka** [comment]
I think this can be closed now that PR #229 has been committed, right?

**Pull request closed without merging**
