### PR TITLE
Explcitly extens CLOG in acording to checkpoint nextXid LSN

### PR DESCRIPTION
**Pull request by knizhnik**
refer #1159

### CODE REVIEW

**Comment by hlinnaka** [comment]
Why is this needed?

**Comment by hlinnaka** [comment]
> Why is this needed?

IIRC PostgreSQL always creates a CLOG_ZEROPAGE record to extend the clog as needed. Replaying those records should be enough. Yeah, clearly something is wrong since your script reproduces errors, but I suspect this patch just hides the real problem, whatever that is.

**Comment by knizhnik** [comment]
It is needed because of the following code in xlog_utils:
```
    /// Update next XID based on provided new_xid and stored epoch.
    /// Next XID should be greater than new_xid. This handles 32-bit
    /// XID wraparound correctly.
    ///
    /// Returns 'true' if the XID was updated.
    pub fn update_next_xid(&mut self, xid: u32) -> bool {
        let xid = xid.wrapping_add(XID_CHECKPOINT_INTERVAL - 1) & !(XID_CHECKPOINT_INTERVAL - 1);
        let full_xid = self.nextXid.value;
        let new_xid = std::cmp::max(xid + 1, pg_constants::FIRST_NORMAL_TRANSACTION_ID);
        let old_xid = full_xid as u32;
        if new_xid.wrapping_sub(old_xid) as i32 > 0 {
            let mut epoch = full_xid >> 32;
            if new_xid < old_xid {
                // wrap-around
                epoch += 1;
            }
            let nextXid = (epoch << 32) | new_xid as u64;

            if nextXid != self.nextXid.value {
                self.nextXid = FullTransactionId { value: nextXid };
                return true;
            }
        }
        false
    }
```

It cause storing in checkpoint nextXid which is not yet generated by Postgres and so for which  CLOG_ZEROPAGE record is not yet generated.

**Comment by hlinnaka** [comment]
> It cause storing in checkpoint nextXid which is not yet generated by Postgres and so for which CLOG_ZEROPAGE record is not yet generated.

How does that happen? Why does our `update_next_xid()` see an XID that Postgres hasn't generated yet?

**Comment by knizhnik** [comment]
> 

`xid` is transaction ID of current WAL record forward aligned on XID_CHECKPOINT_INTERVAL = 1024.
Then we increment it:
```
let new_xid = std::cmp::max(xid + 1, pg_constants::FIRST_NORMAL_TRANSACTION_ID);
```

**Comment by knizhnik** [comment]
> > `xid` is transaction ID of current WAL record forward aligned on XID_CHECKPOINT_INTERVAL = 1024. Then we increment it:
> > ```
> > let new_xid = std::cmp::max(xid + 1, pg_constants::FIRST_NORMAL_TRANSACTION_ID);
> > ```
> 
> I see. I think the logic here is wrong. We can advance nextXid in chunks like we do here, but we should never skip the first XID on each clog page. I think that's what this code was supposed to do, but it's off by one. For example, if you pass '100' as the argument to `update_next_xid`, it updates next_xid to 32769, skipping the first XID on the new CLOG page, 32768. Surely the intention was to advance it to 32768.
> 
> I think this same applies to `pg_commit_ts`, BTW. Looking at `commit_ts.c`, each page in `pg_commit_ts` can hold (8192 / 10 = 819). Annoyingly that's not a power of two, which makes the logic a bit more complicated as you have to check for crossing clog and commit_ts pages separately. We don't currently support track_commit_timestamp, though, do we?
> 
> Unit tests for `update_next_xid` would be very helpful.

I am not quite sure that this logic is right, but according to the code of varsup.c nextXid really points to the next xid, i.e. currently assigned xid + 1. And it is saved in checkpoint record. So as far as I understand, invariant is that checkpoint.nextXid is greater than any XID in WAL.
To enforce this invariant we actually do this increment. 
If passed XID is `1024` than alignment it on XID_CHECKPOINT_INTERVAL does nothing. We still need increment to enforce this invariant.

May be we should first increment and then align. But in makes extra conditions on XID_CHECKPOINT_INTERVAL  which should not be large than BLCKSZ*4

**Comment by knizhnik** [comment]
> We don't currently support track_commit_timestamp, though, do we?

Yes, and it was mentioned in your comment:
```
    // SLRUs include pg_clog, pg_multixact/members, and
    // pg_multixact/offsets. There are other SLRUs in PostgreSQL, but
    // they don't need to be stored permanently (e.g. pg_subtrans),
    // or we do not support them in zenith yet (pg_commit_ts).
```

**Comment by hlinnaka** [comment]
>I am not quite sure that this logic is right, but according to the code of varsup.c nextXid really points to the next xid, i.e. currently assigned xid + 1. And it is saved in checkpoint record. So as far as I understand, invariant is that checkpoint.nextXid is greater than any XID in WAL.
>To enforce this invariant we actually do this increment. 
>If passed XID is `1024` than alignment it on XID_CHECKPOINT_INTERVAL does nothing. We still need increment to enforce this invariant.

Agreed.

>May be we should first increment and then align. 

+1

> But in makes extra conditions on XID_CHECKPOINT_INTERVAL  which should not be large than BLCKSZ*4

Yeah, that deserves an assertion or at least a comment.

**Comment by knizhnik** [comment]
Replaced with #1166

**Pull request closed without merging**
