### PR TITLE
Use `mold` instead of default linker

### PR DESCRIPTION
**Pull request by funbringer**

### CODE REVIEW

**Comment by hlinnaka** [comment]
Because it's faster?

**Comment by SomeoneToIgnore** [comment]
Also presumably helps with the memory co sumptuon, see

**Review by SomeoneToIgnore — APPROVED** [review]
When running `cargo test`, some linking is bound to happen also, that place could be adjusted for unified linker's sake, but I don't think it's very important.

**Comment by funbringer** [comment]
> When running cargo test, some linking is bound to happen also, that place could be adjusted for unified linker's sake, but I don't think it's very important.

Yeah, I'm still trying to figure out why that is the case; since we already build tests in a preceding step (grep `cargo build --bins --tests`).

**Comment by SomeoneToIgnore** [comment]
Indeed, never mind me then.

**Pull request merged**
