### PR TITLE
Build zenithdb/zenith:latest in CI (zenithdb/console#125)

### PR DESCRIPTION
**Pull request by ololobus**
Resolve zenithdb/console#18

### CODE REVIEW

**Comment by ololobus** [comment]
It works now, but I wasn't able to make it complete faster than 20m even with usage of pre-built image with postgres and rust dependencies installed. I've also did it with and without cargo-chief.

For some reason Docker doesn't use cached layers for postgres and rust deps for repetitive builds, when nothing has changed in vendor/postgres and Cargo.*

**Comment by kelvich** [comment]
> For some reason Docker doesn't use cached layers for postgres and rust deps for repetitive builds, when nothing has changed in vendor/postgres and Cargo.*

I think something is created in this directories during build that changes directory checksum and forces rebuild. I use special docker image to list all files that are copied to debug same behavior. I'll take a look

**Comment by ololobus** [comment]
The last build finished in 4 minutes. Probably I've changed something in the zenithdb/build:buster and pushed it to the Docker Hub, which triggered all layers rebuilding on the next run. So it seems that you have to just forget about it, @kelvich :) Sorry, my bad

**Comment by ololobus** [comment]
It seems that caching works fine. I've also added docs, so I'm going to merge this if there are objections

**Pull request merged**
