### PR TITLE
Redo set vm bits

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Comment by lubennikovaav** [comment]
The fix in the last 2 commits looks correct to me,
but this PR contains some unrelated commits. Could you please fix it?

**Comment by knizhnik** [comment]
> The fix in the last 2 commits looks correct to me, but this PR contains some unrelated commits. Could you please fix it?

Done.

**Comment by knizhnik** [comment]
Looks like special handling of XLH_INSERT_ALL_FROZEN_SET bit is really not needed.
I have tested VACUUM FREEZE and COPY (FREEZE ON) commands and in both cases VM
is properly updated without this fix. In both cases visibility map is explicitly updated by Heap2/VISIBLE
WAL record.

So looks like SetVisibilityMapFlags is really not needed.
But I am still going to remove check for XLH_INSERT_ALL_FROZEN_SET  from walingest, because
clearing VM on XLH_INSERT_ALL_FROZEN_SET seems to be really strange behavior.

**Comment by knizhnik** [comment]
Replaced with #1126

**Pull request closed without merging**
