### PR TITLE
reenable parallel test runs in CI

### PR DESCRIPTION
**Pull request by LizardWizzard**

### CODE REVIEW

**Comment by LizardWizzard** [comment]
it looks like after #633 it works smoothly

I've ran several CI rounds and there was no failures

cc @arssher @kelvich

**Comment by kelvich** [comment]
Yeah, let's try again

**Review by kelvich — APPROVED** [review]

**Comment by hlinnaka** [comment]
We probably try to run the 'benchmarks' test suite in parallel, there's too much chance of tests interfering with each other. Also, it looks like we don't print the test results from the 'benchmarks' test anymore.

**Comment by arssher** [comment]
> Also, it looks like we don't print the test results from the 'benchmarks' test anymore.

From all tests, I think, as pytest-xdist swallows stdout, see
https://github.com/pytest-dev/pytest-xdist/issues/402
https://stackoverflow.com/questions/36726461/how-to-print-output-when-using-pytest-with-xdist

Seems like we need to write only to stderr (which may be another reason to adopt `logging`, which I find useful anyway, e.g. to print timestamps) or invent something else.

**Comment by LizardWizzard** [comment]
> From all tests, I think, as pytest-xdist swallows stdout,

Benchmark report is written using special hook see https://github.com/zenithdb/zenith/blob/main/test_runner/fixtures/benchmark_fixture.py#L165. So this shouldn't be a problem with stdout.

I'll look at this. One of the options is just disabling parallelization for performance tests

**Comment by arssher** [comment]
I mean, stdout currently is quite valuable for all tests to investigate problems, not only for performance tests -- we should keep the content.

**Comment by LizardWizzard** [comment]
Yeah, I agree, just to mention that this is not an issue in that particular case

**Pull request merged**
