### PR TITLE
Refactor ObjectTags, intruducing a new concept called "relish"

### PR DESCRIPTION
**Pull request by hlinnaka**
This clarifies - I hope - the abstractions between Repository and
ObjectRepository. The ObjectTag struct was a mix of objects that could
be accessed directly through the public Timeline interface, and also
objects that were created and used internally by the ObjectRepository
implementation and not supposed to be accessed directly by the
callers.  With the RelishTag separaate from ObjectTag, the distinction
is more clear: RelishTag is used in the public interface, and
ObjectTag is used internally between object_repository.rs and
object_store.rs, and it contains the internal metadata object types.

One awkward thing with the ObjectTag struct was that the Repository
implementation had to distinguish between ObjectTags for relations,
and track the size of the relation, while others were used to store
"blobs".  With the RelishTags, some relishes are considered
"non-blocky", and the Repository implementation is expected to track
their sizes, while others are stored as blobs. I'm not 100% happy with
how RelishTag captures that either: it just knows that some relish
kinds are blocky and some non-blocky, and there's an is_block()
function to check that.  But this does enable size-tracking for SLRUs,
allowing us to treat them more like relations.

This changes the way SLRUs are stored in the repository. Each SLRU
segment, e.g. "pg_clog/0000", "pg_clog/0001", are now handled as a
separate relish.  This removes the need for the SLRU-specific
put_slru_truncate() function in the Timeline trait. SLRU truncation is
now handled by caling put_unlink() on the segment. This is more in
line with how PostgreSQL stores SLRUs and handles their trunction.

The SLRUs are "blocky", so they are accessed one 8k page at a time,
and repository tracks their size. I considered an alternative design
where we would treat each SLRU segment as non-blocky, and just store
the whole file as one blob. Each SLRU segment is up to 256 kB in size,
which isn't that large, so that might've worked fine, too. One reason
I didn't do that is that it seems better to have the WAL redo
routines be as close as possible to the PostgreSQL routines. It
doesn't matter much in the repository, though; we have to track the
size for relations anyway, so there's not much difference in whether
we also do it for SLRUs.

# Review guide
This is a big patch, but it's mostly very mechanical code churn, replacing ObjectTags with RelishTags. For the substance, please start from `relishes.rs`. It has comments explaining the concept.

I ended up doing this when I started to rebase the 'layered-repo' branch over the non-rel changes in main. I didn't like how the SLRUs were treated specially, with the special way they were truncated, and this kind of ballooned from there. We had discussions on this earlier, when the ObjectTags were introduced in PR #268, but back then I was not able to articulate my criticism so clearly, and didn't have a good alternative in mind. I think this fixes some of the "layering violations" between the Repository/Timeline traits and the ObjectRepository/ObjectStore implementation of those traits.

Does anyone come with a better name for a "relish"? Something that would capture "a relation, or one of the other files that we store in the repository"? I considered just "file", but then you might expect a more POSIX-like API. I also considered "object", but "object" is an overloaded term, and it would differ from the way the term "object" is currently used. (Currently, an ObjectTag refers to an individual page in a relation (or one of the other things that are not relations), whereas a relish represents the relation itself). I also considered just calling everything a relation, even things that are not relations in PostgreSQL, but that could also be confusing. I kind of like "relish", but I'm not sure how it sounds to others or if it the connotation to food is too strong :-).

### CODE REVIEW

**Comment by hlinnaka** [comment]
While working on this I noticed that current code didn't handle XID wraparound correctly for `pg_multixact/offsets` and `pg_clog` truncation. That needs to be fixed. I didn't try to fix it in this PR, and I didn't bother to refactor the existing broken code either so I just commented out the broken code with a FIXME comment.

**Comment by knizhnik** [comment]
I will look at this more precisely tomorrow, but can you explain me please why this tags are called "relish"?
Shame on me, I never have heard this word before and Google Translate gives me the following synonyms:
enjoy, relish, delight, savor, revel, take pleasure in... which are not somehow associated with object tags in my mind:)

**Comment by kelvich** [comment]
-ish suffix add sense of "kind of" or "like", in other words Relish -> KindOfRelationButNotExactly

**Comment by knizhnik** [comment]
> -ish suffix add sense of "kind of" or "like", in other words Relish -> KindOfRelationButNotExactly
Got it. But I afraid that it can confuse not only me:)

**Comment by lubennikovaav** [comment]
> Does anyone come with a better name for a "relish"?

1. What about something like SegmentedObjectTag?
I found "relish" name confusing, because we consistently refer to SLRUs as "non-rels" to differ them from tables and indexes.  And this new name suggests that they are "rel-like".

2. Also, how does "Checkpoint" belong to this structure? I wouldn't expect to find it there. What is it that these objects really have in common?

3. FWIW, I also think that ObjectTag and object_store names are too generic and we may want to change it to something more specific. One more reason is that "object" and "object storage" is commonly associated with s3 (as in "s3 - cloud object storage")

P.S. I kindly ask you to queue this PR after my refactoring in #344

**Comment by kelvich** [comment]
> What about something like SegmentedObjectTag?

May be just PageTag? Would work both for rel and non-rel (however a bit of stretch for 2PC records)

**Comment by lubennikovaav** [comment]
> > What about something like SegmentedObjectTag?
> 
> May be just PageTag? Would work both for rel and non-rel (however a bit of stretch for 2PC records)

Nope. PageTag is kind of what we're trying to differentiate from.

**Comment by hlinnaka** [comment]
> > Does anyone come with a better name for a "relish"?
> 
>     1. What about something like SegmentedObjectTag?

'SegmentedObjectTag' has all the same problems as 'ObjectTag'. And not all the "relishes" are divided into segments, anyway.

>        I found "relish" name confusing, because we consistently refer to SLRUs as "non-rels" to differ them from tables and indexes.  And this new name suggests that they are "rel-like".

They are "rel-like" because they are stored in the zenith repository alongside with relations. The SLRUs are stored exactly the same as relations. (Before this PR, SLRU truncation was handled differently, but that's no longer the case)

>     2. Also, how does "Checkpoint" belong to this structure? I wouldn't expect to find it there. What is it that these objects really have in common?

Well, we store the Checkpoint in the repository, along with the relations, the SLRUs et al. From the storage point of view, it's stored and versioned by LSN just like all the other relishes. There is no corresponding file in a PostgreSQL data directory, but at the level of the Repository/Timeline abstraction, it doesn't matter.

>     3. FWIW, I also think that ObjectTag and object_store names are too generic and we may want to change it to something more specific. One more reason is that "object" and "object storage" is commonly associated with s3 (as in "s3 - cloud object storage")

True.

> P.S. I kindly ask you to queue this PR after my refactoring in #344

Ok.

**Comment by hlinnaka** [comment]
> > > What about something like SegmentedObjectTag?
> > 
> > 
> > May be just PageTag? Would work both for rel and non-rel (however a bit of stretch for 2PC records)
> 
> Nope. PageTag is kind of what we're trying to differentiate from.

Right, the RelishTag does *not* include the block number.

I also considered just calling the struct RelTag, and calling all the SLRUs, twophase state files etc. also relations. But that's also confusing in the places that actually need to distinguish relations and non-relations.

**Comment by lubennikovaav** [comment]
I've attempted to summarize what combinations we store now in the object store (prior to this PR).

**Tag (aka Key in one zenith timeline) - Value**
- TimelineMetadataTag - TimelineMetadata
- RelationMetadata - RelationSize (nblocks or Unlink)
- RelationBuffer - Page (page image or WAL record)
- Checkpoint - Page (Checkpoint struct as a "page image" or WAL record) 
- ControlFile - Page (ControlFileData struct as a "page image" or WAL record) 
- FilenodeMap - Page(pg_filenode.mao as a "page image" or WAL record)
- Clog. MultiXactMembers, MultiXactOffset - Page (slru page or wall record) or SLRUTruncate
- TwoPhase - Page (full pg_twophase segment as "page image" or wall record)

@hlinnaka, @knizhnik , please correct me, if anything is wrong.

IIUC
Of all tags only RelationBuffer() and TimelineMetadata() are actually used by public Timeline interface.
While others are specific to ObjectRepository implementation. This PR suggests hiding them under one tag "Relish".

What about calling them "PrivateObjectTag" or "InternalObjectTag" then?

**Comment by knizhnik** [comment]
> I've attempted to summarize what combinations we store now in the object store (prior to this PR).
> 
> **Tag (aka Key in one zenith timeline) - Value**
> 
>     * TimelineMetadataTag - TimelineMetadata
> 
>     * RelationMetadata - RelationSize (nblocks or Unlink)
> 
>     * RelationBuffer - Page (page image or WAL record)
> 
>     * Checkpoint - Page (Checkpoint struct as a "page image" or WAL record)
> 
>     * ControlFile - Page (ControlFileData struct as a "page image" or WAL record)
> 
>     * FilenodeMap - Page(pg_filenode.map as a "page image" or WAL record)
> 
>     * Clog. MultiXactMembers, MultiXactOffset - Page (slru page or WAL record) or SLRUTruncate
> 
>     * TwoPhase - Page (full pg_twophase segment as "page image" or WAL record)
> 
> 
> @hlinnaka, @knizhnik , please correct me, if anything is wrong.
> 
> IIUC
> Of all tags only RelationBuffer() and TimelineMetadata() are actually used by public Timeline interface.
> While others are specific to ObjectRepository implementation.
> This PR suggests hiding them under one tag "Relish" and also get rid of SLRUTruncate in favor of RelationSize (unlink).
> 
> What about calling them "PrivateObjectTag" or "InternalObjectTag" then?

I am +1 for InternalTag

**Comment by hlinnaka** [comment]
> I've attempted to summarize what combinations we store now in the object store (prior to this PR).

thanks!

> **Tag (aka Key in one zenith timeline) - Value**
> 
>     * TimelineMetadataTag - TimelineMetadata
>     * RelationMetadata - RelationSize (nblocks or Unlink)
>     * RelationBuffer - Page (page image or WAL record)
>     * Checkpoint - Page (Checkpoint struct as a "page image" or WAL record)
>     * ControlFile - Page (ControlFileData struct as a "page image" or WAL record)
>     * FilenodeMap - Page(pg_filenode.map as a "page image" or WAL record)
>     * Clog. MultiXactMembers, MultiXactOffset - Page (slru page or WAL record) or SLRUTruncate
>     * TwoPhase - Page (full pg_twophase segment as "page image" or WAL record)
> 
> @hlinnaka, @knizhnik , please correct me, if anything is wrong.
> 
> IIUC
> Of all tags only RelationBuffer() and TimelineMetadata() are actually used by public Timeline interface.
> While others are specific to ObjectRepository implementation.

Not quite. These are accessed through the public Timeline interface:

RelationBuffer, Checkpoint, ControlFile, FilenodeMap, Clog, MultiXactMembers, MultiXactOffset and TwoPhase

Of these, only RelationBuffer is requested over the network by the compute node. The others are used to build the base backup tarball. But that distinction is not important to the Repository/Timeline implementation.

RelationMetadata and TimelineMetadata are internal to the ObjectRepository implementation.

> This PR suggests hiding them under one tag "Relish" and also get rid of SLRUTruncate in favor of RelationSize (unlink).

That's right.

> What about calling them "PrivateObjectTag" or "InternalObjectTag" then?

That's fine for RelationMetadata and TimelineMetadata, but the question remains: what do you call the others?

**Comment by kelvich** [comment]
> > > > What about something like SegmentedObjectTag?
> > > 
> > > 
> > > May be just PageTag? Would work both for rel and non-rel (however a bit of stretch for 2PC records)
> > 
> > 
> > Nope. PageTag is kind of what we're trying to differentiate from.
> 
> Right, the RelishTag does _not_ include the block number.

Gotcha. Then I guess made-up work like RelishTag would work along with explanation. Or RelzTag/ZRelTag.

**Comment by lubennikovaav** [comment]
> That's fine for RelationMetadata and TimelineMetadata, but the question remains: what do you call the others?

Checkpoint, ControlFile, FilenodeMap, Clog, MultiXactMembers, MultiXactOffset and TwoPhase -  are NonRels
and we want to unite them with RelationMetadata, right?

maybe some  "PGObjectMetadataTag"  or just "PGObjectTag" ?

So we will have three tags on the upper level:
- TimelineMetadataTag
- ObjectMetadataTag
- Buffer (in your PR) which I propose to rename to BufferDataTag (BufferTag would be better, but it's already taken)

**Comment by hlinnaka** [comment]
> > That's fine for RelationMetadata and TimelineMetadata, but the question remains: what do you call the others?
> 
> Checkpoint, ControlFile, FilenodeMap, Clog, MultiXactMembers, MultiXactOffset and TwoPhase - are NonRels
> and we want to unite them with RelationMetadata, right?

Right. Well, we only need the RelationMetadata the SLRUs, the other relishes are "non-blocky", meaning they are not divided into multiple blocks, and hence we don't need to track their sizes separately.

> maybe "PGObjectMetadataTag" or just "PGObjectTag" ?
> 
> So we will have three tags on the upper level:
> 
>     * TimelineMetadataTag
> 
>     * PGObjectTag
> 
>     * Buffer (in your PR) which I propose to rename to BufferDataTag (BufferTag would be better, but it's already taken)

If we keep the RelishTag struct as it is in this PR, I think PGObjectTag should be RelishMetadata(RelishTag). If we want to rename Buffer, I'd propose Page or Block. So ObjectTag would be:

```
/// key type used by ObjectRepository when it stores pages and metadata in the key-value store
pub struct ObjectKey {
    pub timeline: ZTimelineId,
    pub tag: ObjectTag,
}
...
pub enum ObjectTag {
    // dummy tag preceeding all other keys
    First,

    // Metadata about a timeline. Not versioned.
    TimelineMetadata,

    // These objects store metadata about one relish. Currently it's used
    // just to track the relish's size. It's not used for non-blocky relishes
    // at all.
    RelishMetadata(RelishTag),

    // These are the pages exposed in the public Repository/Timeline interface.
    Block(RelishTag, u32),
}
```
Note: ObjectTag and ObjectKey will go away with the new storage format. It's not based on a key-value store, and it tracks the relation sizes differently.

**Comment by lubennikovaav** [comment]
>  // These objects store metadata about one relish. Currently it's used
>     // just to track the relish's size. It's not used for non-blocky relishes
>     // at all.
>     RelishMetadata(RelishTag),
> 
>     // These are the pages exposed in the public Repository/Timeline interface.
>     Block(RelishTag, u32),


Do you see any issues with this naming? Sorry for this long discussion about naming, but I'd like to avoid introducing one more concept and keyword, if we can.
```
//Metadata about one postgresql object (rel or non-rel) 
// that is used just to track object's size in number of blocks.
PgObjectMetadata(PgObjectTag),

// These are the pages (or WAL-records) exposed in the public Repository/Timeline interface. 
Buffer(PgObjectTag, u32)
```

Buffer sounds better than Block to me just because it may contain not only a regular 8k block but something else (i.e. wal-record or twophase segment data)

**Review by knizhnik — COMMENTED** [review]
First of all I thin it is necessary to strictly enumerate issues and goals we are going to address with the proposed refactoring. From your description, I can extract three points, please correct me if I am wrong:
1. Mix of public and private objects
2. Mix of "BLOBs" and "relations", or better say blocky and non-blocky objects
3. Presence of special method for SLRU truncation
From my point of  view 1) and 3) are not a problem at all. Truncation of SLRU segment is semantically very different from dropping or truncation relation, so I do not sees something awkward in having separate method for it. Public and private usage should not also affect API, and may be some accessors which are now private will be made to other components in future.

So actually we have only one issue: blocky vs non blocky. And I also do not see big problem here. Any non-blocky object can be considered as blocky with size=1 block. Certainly object store needs to do some extra job to maintain size of blocky objects. But here you and I prefer different approaches. I do no like the idea of maintaining relation metadata. It adds a lot of extra complexity and have huge negative impact on performance. And it is actually needed only for relation truncation, because in all other cases relation size can be easily calculated (just last block number+1). Relation truncation happens relatively rare (comparing with inserts/updates), so the solution with storing special truncate marker from my point of view is much better. And it completely eliminates the problem with relation metadata which we are going to solve now. 

Now concerning alternative design of SRLUs when SLRU object corresponds to segment and not block. From my point of view, if we are doing such massive refactoring, then splitting SLRU in segments rather than in block in our object storage is better approach. We do not need to access SLRUs by pages and reconstructing segments from blocks in basebackup only adds extra head ache. I do not consider similarity with correspondent postgres redo handlers as enough motivation. This code is still written mostly from scratch and is not just port of correspondent C code fragments. Actually the difference is mostly module divisor (segment or block size).

Also I do not like that new approach requires nested lookups in one of the most performance critical functions: generation of tarball for spawn of new node (which determines node restart time). Before "relish" there was just one iteration through KV storage, Now for each SRLU we perform separate lookup for each segment. I am not sure if this difference is measurable, but why to try to do something in more complex and less efficient way if simpler solution exists? Especially if we are replacing existed more efficient code...

May be I missed something and your layered storage really needs such representation. But right now advantages of the proposed "relish" evolution are not clear to me.

**Comment by hlinnaka** [comment]
On 22/07/2021 16:00, Konstantin Knizhnik wrote:
> ***@***.**** commented on this pull request.
> 
> First of all I thin it is necessary to strictly enumerate issues and 
> goals we are going to address with the proposed refactoring. From your 
> description, I can extract three points, please correct me if I am wrong:
> 
>  1. Mix of public and private objects
>  2. Mix of "BLOBs" and "relations", or better say blocky and non-blocky
>     objects
>  3. Presence of special method for SLRU truncation
>      From my point of view 1) and 3) are not a problem at all.
>     Truncation of SLRU segment is semantically very different from
>     dropping or truncation relation, so I do not sees something awkward
>     in having separate method for it. Public and private usage should
>     not also affect API, and may be some accessors which are now private
>     will be made to other components in future.

The SLRU truncation is problematic for the layered-repo implementation. 
If we treat the whole SLRU as one relation/file/relish, it will need a 
concept of "missing" pages in the middle. That's doable, of course, but 
it's a weird corner case I'd rather avoid.

> Now concerning alternative design of SRLUs when SLRU object corresponds 
> to segment and not block. From my point of view, if we are doing such 
> massive refactoring, then splitting SLRU in segments rather than in 
> block in our object storage is better approach. We do not need to access 
> SLRUs by pages and reconstructing segments from blocks in basebackup 
> only adds extra head ache. I do not consider similarity with 
> correspondent postgres redo handlers as enough motivation. This code is 
> still written mostly from scratch and is not just port of correspondent 
> C code fragments. Actually the difference is mostly module divisor 
> (segment or block size).

Ok, we can try that. I don't think it makes much difference.

> Also I do not like that new approach requires nested lookups in one of 
> the most performance critical functions: generation of tarball for spawn 
> of new node (which determines node restart time). Before "relish" there 
> was just one iteration through KV storage, Now for each SRLU we perform 
> separate lookup for each segment. I am not sure if this difference is 
> measurable, but why to try to do something in more complex and less 
> efficient way if simpler solution exists? Especially if we are replacing 
> existed more efficient code...

Meh, it's not really performance critical. And easy to improve if it 
turns out to be a problem.

- Heikki

**Comment by knizhnik** [comment]
> The SLRU truncation is problematic for the layered-repo implementation.
If we treat the whole SLRU as one relation/file/relish, it will need a
concept of "missing" pages in the middle. That's doable, of course, but
it's a weird corner case I'd rather avoid.

Do you mean missing blocks or missing segments? There are should not be missing segments, because we are always truncating data from one side and appending to another. Concerning missing pages in the middle of segment, also not quite clear to me how them can arrive, but does filling the whole segment with zeroes solve this problem?

> Meh, it's not really performance critical. And easy to improve if it
turns out to be a problem.

I can't agree that it is not performance critical: adding relation metadata cache increase speed more than two times. If it was not performance critical, then such optimization will have no effect. For SLRUs IMHO it is just useless work, especially if we will associate SLRU objects with segments.In this case there is no need to track SLRU size at all (if we treat each SRLU segment as separate fixed size object).

**Comment by hlinnaka** [comment]
On 22/07/2021 16:50, Konstantin Knizhnik wrote:
>     The SLRU truncation is problematic for the layered-repo implementation.
>     If we treat the whole SLRU as one relation/file/relish, it will need a
>     concept of "missing" pages in the middle. That's doable, of course, but
>     it's a weird corner case I'd rather avoid.
> 
> Do you mean missing blocks or missing segments? There are should not be 
> missing segments, because we are always truncating data from one side 
> and appending to another. Concerning missing pages in the middle of 
> segment, also not quite clear to me how them can arrive, but does 
> filling the whole segment with zeroes solve this problem?

So, we can store the SLRUs in three different granularities in the storage:

1) Treat the whole SLRU as one relish, divided into blocks. This is the 
model we have on 'main' now.

2) Treat each SLRU segment as a separate relish, divided further into 
blocks. This is what I'm proposing in this PR.

3) Treat each SLRU segment as a separate relish, not divided into 
blocks, just stored as one big blob.

With model 1), you need some way to represent the missing pages in the 
middle of the SLRU. For example, in PostgreSQL after XID wraparound you 
might have CLOG segments in the range 0F12-0010. In order to store that, 
you need a way to represent that the blocks belonging to those segments 
are in use, and the others, between 0010-0F12 are not. A simple relation 
size won't do. We're currently doing that with the put_slru_trunction(), 
it effectively punches a hole in the middle of the relish, storing a 
0-sized page there.

With models 2) and 3), it's more straightforward. When a segment is 
truncated away, it's unlinked, just like a dropped relation.

- Heikki

PS. in get_page_at_lsn() you return an 8k all-zeros page for SLRU pages 
that have been removed with put_slru_truncation(), but the comment in 
add_slru_segment() suggests that you would use a zero-length page for 
that. I think one of them is wrong.

**Comment by knizhnik** [comment]
> On 22/07/2021 16:50, Konstantin Knizhnik wrote: The SLRU truncation is problematic for the layered-repo implementation. If we treat the whole SLRU as one relation/file/relish, it will need a concept of "missing" pages in the middle. That's doable, of course, but it's a weird corner case I'd rather avoid. Do you mean missing blocks or missing segments? There are should not be missing segments, because we are always truncating data from one side and appending to another. Concerning missing pages in the middle of segment, also not quite clear to me how them can arrive, but does filling the whole segment with zeroes solve this problem?
> So, we can store the SLRUs in three different granularities in the storage: 1) Treat the whole SLRU as one relish, divided into blocks. This is the model we have on 'main' now. 2) Treat each SLRU segment as a separate relish, divided further into blocks. This is what I'm proposing in this PR. 3) Treat each SLRU segment as a separate relish, not divided into blocks, just stored as one big blob. With model 1), you need some way to represent the missing pages in the middle of the SLRU. For example, in PostgreSQL after XID wraparound you might have CLOG segments in the range 0F12-0010. In order to store that, you need a way to represent that the blocks belonging to those segments are in use, and the others, between 0010-0F12 are not. A simple relation size won't do. We're currently doing that with the put_slru_trunction(), it effectively punches a hole in the middle of the relish, storing a 0-sized page there. With models 2) and 3), it's more straightforward. When a segment is truncated away, it's unlinked, just like a dropped relation. - Heikki PS. in get_page_at_lsn() you return an 8k all-zeros page for SLRU pages that have been removed with put_slru_truncation(), but the comment in add_slru_segment() suggests that you would use a zero-length page for that. I think one of them is wrong.

I mean 3). 
I do not see reasons in scattering segment into blocks if we do not need page access.

**Comment by hlinnaka** [comment]
Rebased.

> I mean 3).
> I do not see reasons in scattering segment into blocks if we do not need page access.

Ok, I just tried doing that. Some functions become a bit simpler, like `import_slru_file` and `add_slru_segment`. But in `save_decoded_record`, the handling of the ZEROPAGE records for the SLRUs become a bit more complicated, as you cannot just do `put_page_image(..., ZERO_PAGE)` to extend the SLRU anymore. Seems better to not do that.

**Comment by hlinnaka** [comment]
We didn't come up with better names for "relishes" or the other structs, so I pushed this. Thanks for the reviews!

**Pull request merged**
