### PR TITLE
Decouple GC and Checkpointer

### PR DESCRIPTION
**Pull request by lubennikovaav**
- Change hardcoded OLDEST_INMEM_DISTANCE value to pageserver config option checkpoint_distance.
- Get rid of 'force' flag in checkpoint_internal(). Use checkpoint_distance=0 instead.
- Run GC and checkpointer in separate threads.
- Add checkpoint_period configuration parameter

### CODE REVIEW

**Comment by lubennikovaav** [comment]
I think we should go further and split Checkpointer into two threads: Checkpointer and GC. 
And also add `checkpoint_period` (checkpoint_timeout ?) config parameter.

@knizhnik, @hlinnaka, what do you think?

**Comment by knizhnik** [comment]
> I think we should go further and split Checkpointer into two threads: Checkpointer and GC.
> And also add `checkpoint_period` (checkpoint_timeout ?) config parameter.
> 
> @knizhnik, @hlinnaka, what do you think?

Yes, I think that them should be performed by  separate threads.
Right now GC with its gcperiod actually blocking checkpointing which cause memory overflow doesn't mater which value of  `checkpoint_distance` you have specified

**Review by knizhnik — APPROVED** [review]
Just two comments:
1. Using i128 for checkpoint_distance seems to be overkill. I think that it was a joke or somebody just wanted to test support 128-bit number on Rust. None of modern computer are able to address i64 (and I do not expect that it will happen i next 10 years). In any case LSN in Postgres is 64 bit.
2. Introducing checkpoint_disatance parameter can not itself decouple GC and checkpointing: we need to launch two separate threads for them.

**Comment by lubennikovaav** [comment]
> Just two comments:
> 
>     1. Using i128 for checkpoint_distance seems to be overkill. I think that it was a joke or somebody just wanted to test support 128-bit number on Rust. None of modern computer are able to address i64 (and I do not expect that it will happen i next 10 years). In any case LSN in Postgres is 64 bit.

Makes sense. I changed it to u64 as in gc_horizon.

>     2. Introducing checkpoint_disatance parameter can not itself decouple GC and checkpointing: we need to launch two separate threads for them.

Done.

**Pull request merged**
