### PR TITLE
More failsafe relish_storage impls

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Follow up of https://github.com/zenithdb/zenith/pull/639#pullrequestreview-769259701

### CODE REVIEW

**Comment by patins** [comment]
Is local storage strictly for dev/testing? Does it need these semantics?

**Comment by SomeoneToIgnore** [comment]
Yep, the local storage is a thing for local testing only currently.

Not sure what do you mean about semantics, better error messages?

**Comment by patins** [comment]
Semantics as in does it need to be crash safe?

**Comment by SomeoneToIgnore** [comment]
Oh, got it, thanks.

Yes, local storage at its current state duplicates the workdir manipulations pageserver does when dealing with layers, and we care the s3 impl only in production now.

So consistency feels pretty redundant at this point, I've tried to apply it to verify I'm doing things right and to bring some level of parity to future IT tests for the feature.

**Comment by SomeoneToIgnore** [comment]
So looks like we will be changing the S3 file format eventually, according to the discussion around

https://discord.com/channels/869525774699462656/869526396878323733/895643938554253312 

Also, we slow down things when syncing per-file too if I remember, so is local storage sync when downloading necessary now in your opinion, @patins ?

**Comment by SomeoneToIgnore** [comment]
I'll close this one for now then, to avoid confusion.

**Pull request closed without merging**
